[custom]
;解决DNS泄露，无分流群组
  ruleset=REJECT,https://raw.githubusercontent.com/ionull/change/main/ad.list
  ;ruleset=🐷 本不应该,https://raw.githubusercontent.com/ionull/change/main/unwarranted.list?v=1
  ruleset=DIRECT,https://raw.githubusercontent.com/ionull/change/main/direct.list?v=24
  ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
  ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,services.googleapis.cn
  ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
  ruleset=🇭🇰 HongKong,https://raw.githubusercontent.com/ionull/change/main/hk.list?v=10
  ruleset=🇭🇰 Now,https://raw.githubusercontent.com/ionull/change/main/now.list?v=8
  ruleset=🇭🇰 TVB,https://raw.githubusercontent.com/ionull/change/main/tvb.list?v=1
  ruleset=🇭🇰 RTHK,https://raw.githubusercontent.com/ionull/change/main/rthk.list?v=0
  ruleset=🇸🇬 Singapore,https://raw.githubusercontent.com/ionull/change/main/sg.list
  ruleset=🇸🇬 Star,https://raw.githubusercontent.com/ionull/change/main/star.list?v=0
  ruleset=🌍 TWStream,https://raw.githubusercontent.com/ionull/change/main/tw-stream.list?v=2
  ruleset=DIRECT,[]GEOIP,CN,no-resolve
  ruleset=📺 Taiwan,https://raw.githubusercontent.com/ionull/change/main/tw.list?v=11
  ruleset=🌍 GlobalStream,https://raw.githubusercontent.com/ionull/change/main/global-stream.list?v=14
  ruleset=🐝 Bee,https://raw.githubusercontent.com/ionull/change/main/bee.list?v=6
  ruleset=🐝 Bees,https://raw.githubusercontent.com/ionull/change/main/bees.list?v=0
  ruleset=🦴 Gemini,https://raw.githubusercontent.com/ionull/change/main/gemini.list?v=4
  ruleset=💬 OpenAi,https://raw.githubusercontent.com/ionull/change/main/open.ai.list
  ;ruleset=🎵 Spotify,https://raw.githubusercontent.com/ionull/change/main/jp.list
  ruleset=🎵 Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Spotify/Spotify.list
  ruleset=🎮 Niantic,https://raw.githubusercontent.com/ionull/change/main/niantic.list
  ruleset=🎮 Ingress,https://raw.githubusercontent.com/ionull/change/main/ingress.list
  ruleset=🐲 StreamLink,https://raw.githubusercontent.com/ionull/change/main/stream.list
  ruleset=💰 BN,https://raw.githubusercontent.com/ionull/change/main/bn.list
  ruleset=📱 Telegram,https://raw.githubusercontent.com/Jameshan-112/change/main/tg.list
  ruleset=🔗 CF,https://raw.githubusercontent.com/ionull/change/main/cf.list?v=2
  ruleset=🎬 EMBY,https://raw.githubusercontent.com/Jameshan-112/change/main/emby.list
  ruleset=🚡 下载,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
  ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/Jameshan-112/change/main/m.list
  ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/Jameshan-112/change/main/onedrive.list
  ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
  ;ruleset=🚀 节点选择,https://raw.githubusercontent.com/Hackl0us/SS-Rule-Snippet/refs/heads/main/Rulesets/Surge/Basic/foreign.list
  ruleset=DIRECT,DOMAIN-KEYWORD,m-team
  ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
  ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
  ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
  ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
  ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
  ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
  ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
  ;ruleset=DIRECT,https://raw.githubusercontent.com/Jameshan-112/change/main/chinaip.list
  ruleset=DIRECT,https://raw.githubusercontent.com/Hackl0us/SS-Rule-Snippet/refs/heads/main/Rulesets/Surge/Basic/CN.list
  ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
  ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
  ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
  ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
  ;ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
  ;ruleset=DIRECT,[]GEOSITE,CN
  ruleset=🐟 漏网之鱼,[]FINAL

  custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]♻️ AAuto`[]♻️ CAuto`[]♻️ JAuto`[]♻️ GAuto`[]♻️ CloudFlare`[]♻️ HKAuto`[]♻️ HKAutoS`[]♻️ TWAuto`[]♻️ TWAutoS`(香港|日本|台湾|美国|新加坡|韩国)`[]DIRECT`.*
  custom_proxy_group=🎮 Niantic`select`[]DIRECT`[]♻️ HKAuto`[]♻️ HKAutoS`[]♻️ AAuto`[]♻️ JAuto`[]♻️ GAuto`[]♻️ TWAuto`[]♻️ TWAutoS`(香港|HK|日本|台湾|TW|JP|新加坡|SG)`[]🚀 节点选择`.*
  custom_proxy_group=🎮 Ingress`select`[]DIRECT`[]♻️ HKAuto`[]♻️ HKAutoS`[]♻️ AAuto`[]♻️ JAuto`(香港|HK|日本|台湾|TW|JP|新加坡|SG)`[]🚀 节点选择`.*
  custom_proxy_group=♻️ AAuto`select`[]♻️ A4Auto`[]🐑 Yang`(ff7700d1)`[]♻️ CAuto
  custom_proxy_group=♻️ JAuto`select`[]♻️ J4Auto`(1b301e07)
  custom_proxy_group=♻️ CAuto`select`[]♻️ CFAuto`(counter-fighter)
  custom_proxy_group=🐝 Bee`select`[]♻️ AAuto`[]🐑 Yang`[]♻️ CAuto`[]♻️ CloudFlare`[]♻️ GAuto`[]♻️ TWAuto`[]♻️ TWAutoS`[]DIRECT`(香港|HK|HongKong|台湾|日本)`[]🚀 节点选择`.*
  custom_proxy_group=🐲 StreamLink`select`[]♻️ AAuto`[]♻️ CloudFlare`[]🐑 Yang`(香港|HK|日本|JP|新加坡)`[]🚀 节点选择`[]DIRECT`.*
  custom_proxy_group=🇭🇰 HongKong`select`[]♻️ CAuto`[]♻️ HKAuto`[]♻️ HKAutoS`[]♻️ HKAutoAll`(香港|HK|HongKong)
  custom_proxy_group=🇭🇰 Now`select`[]♻️ CAuto`(香港|HK|HongKong)
  custom_proxy_group=🇭🇰 TVB`select`[]♻️ CAuto`[]♻️ CloudFlare`[]♻️ AAuto`[]♻️ GAuto`[]♻️ HKAuto`[]♻️ HKAutoS`[]♻️ HKAutoAll`[]DIRECT`(香港|HK|HongKong)`[]🚀 节点选择`.*
  custom_proxy_group=🇭🇰 RTHK`select`[]♻️ CAuto`[]DIRECT`[]♻️ HKAuto`[]♻️ HKAutoS`[]♻️ HKAutoAll`(香港|HK|HongKong)
  custom_proxy_group=🇸🇬 Singapore`select`(新加坡)`[]♻️ AAuto
  custom_proxy_group=🇸🇬 Star`select`[]🐑 Yang`[]♻️ JAuto`[]♻️ TWAuto`[]♻️ TWAutoS`[]♻️ HKAuto`[]♻️ HKAutoS`(新加坡)`[]♻️ AAuto`[]🚀 节点选择`[]DIRECT`.*
  custom_proxy_group=🌍 GlobalStream`select`[]♻️ AAuto`[]♻️ CAuto`[]🐑 Yang`[]♻️ JAuto`[]♻️ CloudFlare`[]♻️ GAuto`(香港|HK|HongKong)`[]🚀 节点选择`[]DIRECT`.*
  custom_proxy_group=🌍 TWStream`select`[]♻️ CloudFlare`[]♻️ GAuto`[]♻️ AAuto`[]♻️ TWAutoS`(香港|HK|HongKong|台湾)`[]🚀 节点选择`[]DIRECT`.*
  custom_proxy_group=📺 Taiwan`select`[]♻️ TWAuto`select`[]♻️ TWAutoS`[]♻️ TWAutoAll`(台湾|TW|Taiwan)`[]🚀 节点选择`[]DIRECT`.*
  custom_proxy_group=🐝 Bees`select`[]♻️ AAuto`[]🐑 Yang`[]♻️ CloudFlare`[]♻️ GAuto`[]♻️ TWAuto`[]♻️ TWAutoS`[]DIRECT`(香港|HK|HongKong|台湾|日本)`[]🚀 节点选择`.*
  custom_proxy_group=🦴 Gemini`select`[]♻️ TWAuto`[]♻️ TWAutoS`[]♻️ TWAutoAll`[]♻️ AAuto`[]♻️ JAuto`[]♻️ GAuto`(台湾|TW|Taiwan)`[]🚀 节点选择`[]DIRECT`.*
  custom_proxy_group=📱 Telegram`select`[]♻️ CloudFlare`[]♻️ AAuto`[]♻️ CAuto`[]♻️ JAuto`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`.*
  custom_proxy_group=🎵 Spotify`select`[]♻️ AAuto`[]♻️ GAuto`(美国)`[]🚀 节点选择`[]DIRECT`.*
  custom_proxy_group=💰 BN`select`[]DIRECT`(香港|HK|HongKong)`[]🚀 节点选择`.*
  custom_proxy_group=💬 OpenAi`select`[]♻️ AAuto`[]♻️ TWAuto`[]♻️ TWAutoAll`[]♻️ JAuto`(日本|台湾|美国|新加坡|韩国)`[]🚀 节点选择`[]DIRECT`.*
  custom_proxy_group=🔗 CF`select`[]♻️ CloudFlare`[]♻️ AAuto`[]♻️ CAuto`[]♻️ GAuto`[]DIRECT`(香港|HK|HongKong)`[]🚀 节点选择`.*
  custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]♻️ AAuto`[]♻️ CloudFlare`[]♻️ 自动选择`[]DIRECT`.*
  custom_proxy_group=🎬 EMBY`select`[]♻️ CloudFlare`[]♻️ AAuto`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`.*
  custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`.*
  custom_proxy_group=🚡 下载`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`.*
  custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`.*
  custom_proxy_group=Ⓜ️ 微软云盘`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`.*
  ;custom_proxy_group=🐷 本不应该`select`[]DIRECT`[]♻️ CloudFlare`[]🚀 节点选择`[]♻️ 自动选择`.*
  custom_proxy_group=♻️ CloudFlare`url-test`(-HTTP-|-HTTPS-)`http://www.gstatic.com/generate_204`300
  custom_proxy_group=♻️ CFAuto`url-test`(counter-fighter)`http://www.gstatic.com/generate_204`300
  custom_proxy_group=♻️ A4Auto`url-test`(ff7700d1)`http://www.gstatic.com/generate_204`300
  custom_proxy_group=♻️ J4Auto`url-test`(1b301e07)`http://www.gstatic.com/generate_204`300
  custom_proxy_group=♻️ GAuto`select`[]♻️ G4Auto`(b38531a3)
  custom_proxy_group=♻️ G4Auto`url-test`(b38531a3)`http://www.gstatic.com/generate_204`300
  custom_proxy_group=♻️ TWAuto`url-test`(台湾-0)`http://www.gstatic.com/generate_204`300
  custom_proxy_group=♻️ TWAutoAll`url-test`(台湾)`http://www.gstatic.com/generate_204`300
  custom_proxy_group=♻️ TWAutoS`url-test`(台湾 直连)`http://www.gstatic.com/generate_204`300
  custom_proxy_group=♻️ HKAuto`url-test`(香港-0)`http://www.gstatic.com/generate_204`300
  custom_proxy_group=♻️ HKAutoS`url-test`(香港 直连|IEPL  香港)`http://www.gstatic.com/generate_204`300
  custom_proxy_group=♻️ HKAutoAll`url-test`(香港)`http://www.gstatic.com/generate_204`300
  custom_proxy_group=🐑 Yang`select`(大碗)
  custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300

  enable_rule_generator: true
  overwrite_original_rules: true

  clash_rule_base=https://raw.githubusercontent.com/ionull/change/refs/heads/main/base.yml?v=12
  ;surge_rule_base=base/surge.conf
  ;surfboard_rule_base=base/surfboard.conf
  ;mellow_rule_base=base/mellow.conf
  ;quan_rule_base=base/quan.conf
  quanx_rule_base=https://raw.githubusercontent.com/ionull/change/refs/heads/main/qx.conf?v=10
  loon_rule_base=https://raw.githubusercontent.com/ionull/change/refs/heads/main/lon.conf?v=6
